-- Run this entire script in Supabase: SQL Editor > New query > Run.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  admission_no text unique not null,
  student_name text not null,
  date_of_birth date,
  gender text,
  curriculum text,
  class_name text,
  parent_name text,
  phone text,
  parent_email text,
  emergency_contact text,
  transport_route text,
  created_at timestamptz default now()
);

create table if not exists public.fees (
  id bigint generated by default as identity primary key,
  payment_date date,
  admission_no text,
  student_name text,
  amount_paid numeric default 0,
  term text,
  balance numeric default 0,
  payment_method text,
  created_at timestamptz default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  attendance_date date,
  admission_no text,
  student_name text,
  status text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  staff_id text unique not null,
  staff_name text not null,
  role text,
  phone text,
  email text,
  salary numeric default 0,
  employment_status text,
  created_at timestamptz default now()
);

create table if not exists public.construction (
  id bigint generated by default as identity primary key,
  record_date date,
  project text,
  contractor text,
  budget numeric default 0,
  amount_spent numeric default 0,
  status text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  item text,
  category text,
  quantity numeric default 0,
  unit_cost numeric default 0,
  total_value numeric default 0,
  location text,
  minimum_stock numeric default 0,
  created_at timestamptz default now()
);

-- Enable Row Level Security.
alter table public.students enable row level security;
alter table public.fees enable row level security;
alter table public.attendance enable row level security;
alter table public.staff enable row level security;
alter table public.construction enable row level security;
alter table public.inventory enable row level security;

-- The Streamlit app uses the anon key. These policies permit the app to read/write.
-- Access is still protected by the app's login screen. Later we can upgrade to Supabase Auth.
do $$
declare t text;
begin
  foreach t in array array['students','fees','attendance','staff','construction','inventory']
  loop
    execute format('drop policy if exists "app full access" on public.%I', t);
    execute format('create policy "app full access" on public.%I for all to anon using (true) with check (true)', t);
  end loop;
end $$;
